### ISSUE TITLE
Uses 100% CPU power

### ISSUE THREAD

**Issue by kylesferrazza** [bthuilot/PythonGames#1]
When either X or O wins, the game doesn't know what to do and ends up eating up 100% of CPU power and fans start spinning
Had to force close to get out of there

**Comment by bthuilot** [comment]
Do you have the latest version of PyGame installed?

**Comment by kylesferrazza** [comment]
Yes I did a fresh
    pip install pygame

**Comment by bthuilot** [comment]
Okay, Try pulling and running again. I initiated fonts and made the loop only run once.
